
-- CONFIRMAR ENTREGA DO PEDIDO

/* REQUISITOS:

    VARIAVEIS:
    - ID_PPD: ID PEDIDO
    - CURRENDATAE: DATA ENTREGA
    - STATUS_PEDIDO: STTS_VENDA 3


*/

CREATE OR REPLACE FUNCTION PEDIDO_ENTREGUE(
    ID_PDD INT
) RETURNS VOID AS $$
DECLARE
    CURRENT_DATE TIMESTAMP;
    STTS_VENDA INT;
BEGIN
    STTS_VENDA = 3;
    CURRENT_DATE := 'NOW';
    UPDATE PEDIDO
    SET DATA_ENTREGA = CURRENT_DATE,
        STATUS_VENDA = STTS_VENDA
    WHERE ID_PEDIDO = ID_PDD;
END $$ LANGUAGE PLPGSQL;
