/* REQUISITOS */

-- 1 - A função deve verificar se todos os dados informado são validos
-- 2 - O atributo usuário deve conter pelo menos 3 caracteres
-- 3 - A senha deve conter pelo menos 6 caracteres
-- 4 - O nome deve conter pelo menos 3 caracteres

/* FUNÇÕES NECESSAŔIAS PARA A RESOLUÇÃO */

-- REGISTRAR_LOJA(USUARIO VARCHAR, SENHA VARCHAR, NOME VARCHAR, DESCRICAO VARCHAR) -> VOID (ESTA É A FUNÇÃO PRINCIPAL)

--===========================================================================================--
CREATE OR REPLACE FUNCTION REGISTRAR_LOJA(
	USUARIO VARCHAR, 
	SENHA VARCHAR, 
	NOME VARCHAR, 
	DESCRICAO VARCHAR
) RETURNS VOID AS $$ 
BEGIN
	IF (USUARIO IS NULL) THEN
		RAISE EXCEPTION 'O VALOR USUARIO NÃO PODE SER NULO, INFORME O USUARIO (ARGUMENTO NA POSICAO 0)';
	ELSIF (SENHA IS NULL) THEN
		RAISE EXCEPTION 'O VALOR SENHA NÃO PODE SER NULO, INFORME UMA SENHA (ARGUMENTO NA POSICAO 1)';
	ELSIF (NOME IS NULL) THEN
		RAISE EXCEPTION 'O VALOR NOME NÃO PODE SER NULO, INFORME O NOME (ARGUMENTO NA POSICAO 2)';
	ELSIF (DESCRICAO IS NULL) THEN
		RAISE EXCEPTION 'O VALOR DESCRICAO NÃO PODE SER NULO, INFORME UMA DESCRICAO (ARGUMENTO NA POSICAO 3)';
	ELSIF (LENGTH(USUARIO) < 3) THEN
		RAISE EXCEPTION 'O VALOR USUÁRIO DEVE TER PELO MENOS 3 CARACTERES';
	ELSIF (LENGTH(SENHA) < 6) THEN
		RAISE EXCEPTION 'A SENHA DEVE TER PELO MENOS 6 CARACTERES';
	ELSIF (LENGTH(NOME) < 3) THEN
		RAISE EXCEPTION 'O NOME DEVE TER PELO MENOS 3 CARACTERES';
	END IF;
	
	INSERT INTO LOJA 
		(USUARIO, SENHA, NOME, DESCRICAO)
	VALUES 
		(USUARIO, SENHA, NOME, DESCRICAO);
		
	RAISE INFO 'LOJA REGISTRADA COM SUCESSO!';
END;
$$ LANGUAGE PLPGSQL;
